/* tslint:disable */
/* eslint-disable */
/**
 * Test Swagger API
 * Test for using swagger-codegen to auto-generate API interface, and use swagger-ui to show and test API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    data?: string;
}
